version: '3'
services:
  sensu-backend:
    image: "sensu/sensu:latest"
    ports:
      - "3000:3000"
      - "2379:2379"
      - "2380:2380"
      - "8080:8080"
      - "8081:8081"
    command: "sensu-backend start"
    volumes:
      - "./tmp/sensu:/var/lib/sensu"
    hostname: sensu-backend
  sensu-agent:
    image: "sensu/sensu:latest"
    ports:
      - "3031:3031"
    command: "sensu-agent start --backend-url ws://sensu-backend:8081 --subscriptions dev,poller,system,linux,docker --cache-dir /var/lib/sensu --namespace default --deregister true --api-host 0.0.0.0"
    links:
      - "sensu-backend:backend"
    depends_on:
      - sensu-backend
    hostname: sensu-agent
  snmpsim:
    image: tandrup/snmpsim
    platform: "linux/amd64"
    ports:
    - 161:161/udp
  snmpsim2:
    image: tandrup/snmpsim
    platform: "linux/amd64"
    ports:
    - 162:161/udp
  snmp_exporter:
    image: ricardbejarano/snmp_exporter
    ports:
    - 9116:9116